### ISSUE TITLE
Fails to parse/run due to non-ASCII/UTF-8 character

### ISSUE THREAD

**Issue by IseyitThe** [3arthqu4ke/headlessmc#149]
issue with the HeadlessMC launcher, which is failing to parse a configuration file due to a non-ASCII/UTF-8 character. The error message indicates that the program is trying to find an enum constant named DİSALLOW, but it doesn't exist, which is caused by the fact that the computer language uses characters like İ Ö Ç etc.

Error:
```C:\Users\Seyit\Desktop\HeadlessMC>java -jar headlessmc-launcher-1.9.5.jar
java.lang.IllegalArgumentException: No enum constant me.earth.headlessmc.launcher.version.Rule.Action.DİSALLOW
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at me.earth.headlessmc.launcher.version.Rule$Action.valueOf(Rule.java:13)
        at me.earth.headlessmc.launcher.version.RuleFactory.parse(RuleFactory.java:42)
        at me.earth.headlessmc.launcher.version.RuleFactory.parse(RuleFactory.java:30)
        at me.earth.headlessmc.launcher.version.LibraryFactory.parse(LibraryFactory.java:39)
        at me.earth.headlessmc.launcher.version.LibraryFactory.parseLibraries(LibraryFactory.java:31)
        at me.earth.headlessmc.launcher.version.VersionFactory.parse(VersionFactory.java:26)
        at me.earth.headlessmc.launcher.version.DefaultVersionFactory.parse(DefaultVersionFactory.java:3)
        at me.earth.headlessmc.launcher.version.VersionService.read(VersionService.java:63)
        at me.earth.headlessmc.launcher.version.VersionService.update(VersionService.java:46)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:21)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:13)
        at me.earth.headlessmc.launcher.Main.runHeadlessMc(Main.java:72)
        at me.earth.headlessmc.launcher.Main.main(Main.java:36)

**Comment by 3arthqu4ke** [comment]
Try the artifcat published here: https://github.com/3arthqu4ke/headlessmc/actions/runs/9963394563 that should fix the issue
