### ISSUE TITLE
Various Issues (Library loading problem, Properties file not getting loaded,...)

### ISSUE THREAD

**Issue by HacktheTime** [3arthqu4ke/headlessmc#150]
This is a bunch of Issues with things I didn't find in my research and things that made me wonder whether they are known.

Other than for the errors I am probably the one doing something wrong but I was not able to find documentation or guide about these things and don't have any other ideas about what I can try.

This is for a Hypixel Bot.
A Bunch of Errors that I got during my tests:

com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
        at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar:?]
        at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
        at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
        at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.<init>(class_310.java:684) ~[client-intermediary.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.11-1.20.4.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'flite':
 at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323) ~[jna-5.13.0.jar:?]
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
        at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
        ... 8 more
        Suppressed: java.lang.UnsatisfiedLinkError: libflite.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
                at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
                at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
                at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
                at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
                at net.minecraft.class_310.<init>(class_310.java:684) ~[client-intermediary.jar:?]
                at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.11-1.20.4.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
        Suppressed: java.lang.UnsatisfiedLinkError: libflite.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
                at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
                at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
                at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
                at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
                at net.minecraft.class_310.<init>(class_310.java:684) ~[client-intermediary.jar:?]
                at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.11-1.20.4.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
 at com.sun.jna.Native.extractFromResourcePath(Native.java:1145) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:295) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
                at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
                at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
                at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
                at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
                at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
                at net.minecraft.class_310.<init>(class_310.java:684) ~[client-intermediary.jar:?]
                at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.11-1.20.4.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]

[16:05:56] [Render thread/WARN]: Missing sound for event: minecraft:entity.generic.wind_burst
[16:05:56] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: OpenAL 1.1 not supported
        at net.minecraft.class_4225.method_19661(class_4225.java:163) ~[client-intermediary.jar:?]
        at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
        at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
        at net.minecraft.class_1144.method_18182(class_1144.java:126) ~[client-intermediary.jar:?]
        at net.minecraft.class_1144.method_18788(class_1144.java:41) ~[client-intermediary.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.11-1.20.4.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]

I want to pair a bot as a service in systemd with a custom user as permission so not root(security ofc). Due to this I need to more or less "just" launch it. I will make a mod that I can talk to how I like BUT that means I need to set up the client too etc. The question is how can I tell headless-mc to authorize with arguments and join mc.hypixel.net with fabric-loader 1.20.4.

I tried to set it up via the properties file like it was talked about. However, It does not seem to work. It seems also possible to use arguments in the launch commands but those didn't work either in my tests.
properties file in: 
/HeadlessMC/configs/config.properties (I also tried LauncherProperties.properties as the name didn't seem to work)
putting it in the config in HeadlessMC/config.properties didn't work either
content:

hmc.email="censored@censored"
hmc.password="censored"
hmc.launchername="fabric-loader-0.15.11-1.20.4"
hmc.gameargs=--quickPlayMultiplayer mc.hypixel.net

nothing of those seems to work. not even log in (obviously with the actual email and password)

PS I also experienced the Unicode character problem but that would probably be hard to reproduce the way I did it. I just for fun logged into Skyblock on a coop and got collections notifications that include Unicode characters I assume by the error.

I tried to find documentation for a while but did not find one and there were no posts about this online anywhere I could see.

**Comment by 3arthqu4ke** [comment]
I do not have the time to help with this rn, but hmc.launchername is the wrong property.
For launching the game directly you need to use the command argument like, `java -jar headlessmc.jar --command "launch ..."`.
Unicode will be fixed in 1.10.0, though I am not sure if you had the same issue.
