### ISSUE TITLE
Getting a lot of errors in console with clean install of headlessmc

### ISSUE THREAD

**Issue by Andrelissss** [3arthqu4ke/headlessmc#188]
running headlessmc without any mods causes error messages to get spammed in console
[aeasdsads.txt](https://github.com/user-attachments/files/16828397/aeasdsads.txt)

**Comment by 3arthqu4ke** [comment]
This one looks odd, not entirely sure whats going on.
```
[10:42:37] [Client thread/INFO] [STDERR]: [net.minecraft.client.gui.GuiNewChat:handler$logChatMessageHook$zzc000:535]: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.out()Lorg/fusesource/jansi/AnsiPrintStream;
[10:42:37] [Client thread/INFO] [STDERR]: [net.minecraft.client.gui.GuiNewChat:handler$logChatMessageHook$zzc000:535]:
at net.kyori.ansi.JAnsiColorLevel.computeFromJAnsi(JAnsiColorLevel.java:50)
[10:42:37] [Client thread/INFO] [STDERR]: [net.minecraft.client.gui.GuiNewChat:handler$logChatMessageHook$zzc000:535]:
at net.kyori.ansi.ColorLevel.compute(ColorLevel.java:207)
[10:42:37] [Client thread/INFO] [STDERR]: [net.minecraft.client.gui.GuiNewChat:ha
```

Will see.

The PatternLayout errors can be ignored if you start with the -log4j flag, i will fix the log4j configuration soon.
These errors are minecraft specific and not my fault:
```
[10:42:57] [Thread-9/ERROR]: Error in class ''
[10:42:57] [Thread-9/ERROR]: Source 'e15c4bb1-71f3-4cf6-88ca-60a05f3fe16a' not found in method 'play'
```

and

```
[10:42:56] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_422]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_422]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.scoreboard.Scoreboard.func_96511_d(SourceFile:229) ~[auo.class:?]
        at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1813) ~[bcy.class:?]
        at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:113) ~[hr.class:?]
        at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:13) ~[hr.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_422]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_422]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 9 more
```

**Comment by Andrelissss** [comment]
is there a way to ignore theese errors in console then?

**Comment by 3arthqu4ke** [comment]
Use the -paulscode flag when launching, should probalby remove the [Thread-9/ERROR]: Source errors, the "[10:42:56] [Client thread/FATAL]: Error executing task" should disappear on their own.

**Comment by Andrelissss** [comment]
Where to use it and does it require any arguments?

**Comment by Andrelissss** [comment]
I added hmc.invert.pauls.flag=true to config.properities now I stopped getting the error that was getting spammed but I still get the errors when switching lobbies but it is way better now at least

**Comment by Andrelissss** [comment]
I would need to disable warnings and other errors from minecraft that are thrown too

**Comment by 3arthqu4ke** [comment]
This is not really in the scope of HeadlessMc anymore as it is Minecraft version and server specific behaviour. You could write a simple mod for this, with a Mixin e.g. at Scoreboard.func_96527_f that prevents this exception from getting logged.
