### ISSUE TITLE
not much of a programmer but wanted to headless baritone then this happened.

### ISSUE THREAD

**Issue by WindowsRefundDay** [3arthqu4ke/HeadlessMc#2]
already created a key in headlessmc/config but [11:35:12] [main/INFO] [ConfigService]: Reading config file: C:\Users\joelj\Desktop\HeadlessMC\config.properties
[11:35:12] [main/INFO] [ConfigService]: Found 1 config(s), active config: config
[11:35:12] [main/INFO] [Main]: Detected: OS(name=Windows 11, type=WINDOWS, version=10.0, arch=true)
[11:35:12] [main/INFO] [Main]: Minecraft Directory: C:\Users\joelj\AppData\Roaming\.minecraft
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "arguments" is null
        at me.earth.headlessmc.launcher.version.ArgumentFactory.parse(ArgumentFactory.java:23)
        at me.earth.headlessmc.launcher.version.VersionFactory.parse(VersionFactory.java:36)
        at me.earth.headlessmc.launcher.version.VersionService.read(VersionService.java:63)
        at me.earth.headlessmc.launcher.version.VersionService.update(VersionService.java:46)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:17)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:21)
        at me.earth.headlessmc.launcher.Main.main(Main.java:39)

**Comment by 3arthqu4ke** [comment]
Please try [this](https://github.com/3arthqu4ke/HeadlessMc/releases/tag/1.0.3a) new version.
