### ISSUE TITLE
1.12.2 xvfb does not work

### ISSUE THREAD

**Issue by 3arthqu4ke** [3arthqu4ke/headlessmc#211]
Can probably be fixed by patching lwjgl in another way?
```
java.lang.ExceptionInInitializerError
	at net.minecraft.client.Minecraft.func_175594_ao(Minecraft.java:680)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:456)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 10 more
```

**Comment by 3arthqu4ke** [comment]
Setting the system property LWJGL_DISABLE_XRANDR to true could also probably fix this but now we got a patch.
