### ISSUE TITLE
Login error in console app

### ISSUE THREAD

**Issue by hub50** [3arthqu4ke/HeadlessMc#24]
When I log in using the console login command, when I enter my correct credentials, one of two errors is thrown which is either 
`Failed to log you in: I/O exception thrown during Microsoft HTTP requests
me.earth.headlessmc.launcher.auth.AuthException: I/O exception thrown during Microsoft HTTP requests
        at me.earth.headlessmc.launcher.auth.AccountManager.login(AccountManager.java:66)
        at me.earth.headlessmc.launcher.command.login.LoginCommand.lambda$login$0(LoginCommand.java:50)
        at me.earth.headlessmc.launcher.command.login.PasswordCommand.execute(PasswordCommand.java:35)
        at me.earth.headlessmc.command.CommandContextImpl.executeCommand(CommandContextImpl.java:43)
        at me.earth.headlessmc.command.CommandContextImpl.execute(CommandContextImpl.java:30)
        at me.earth.headlessmc.command.line.ConsoleListener.listen(ConsoleListener.java:20)
        at me.earth.headlessmc.command.line.CommandLineImpl.listen(CommandLineImpl.java:26)
        at me.earth.headlessmc.launcher.Main.main(Main.java:66)`
or 
`Exception in thread "main" java.lang.IndexOutOfBoundsException: No group 1
        at java.util.regex.Matcher.group(Unknown Source)
        at fr.litarvan.openauth.microsoft.MicrosoftAuthenticator.match(MicrosoftAuthenticator.java:305)
        at fr.litarvan.openauth.microsoft.MicrosoftAuthenticator.loginWithCredentials(MicrosoftAuthenticator.java:119)
        at me.earth.headlessmc.launcher.auth.AccountManager.login(AccountManager.java:58)
        at me.earth.headlessmc.launcher.command.login.LoginCommand.lambda$login$0(LoginCommand.java:50)
        at me.earth.headlessmc.launcher.command.login.PasswordCommand.execute(PasswordCommand.java:35)
        at me.earth.headlessmc.launcher.command.login.PasswordContext.fail(PasswordContext.java:37)
        at me.earth.headlessmc.command.CommandContextImpl.execute(CommandContextImpl.java:37)
        at me.earth.headlessmc.command.line.ConsoleListener.listen(ConsoleListener.java:20)
        at me.earth.headlessmc.command.line.CommandLineImpl.listen(CommandLineImpl.java:26)
        at me.earth.headlessmc.launcher.Main.main(Main.java:66)`
       I cannot log in to my microsoft account and also cannot launch minecraft. How can I resolve this issue? Also, can someone let me know how to use mods if minecraft does launch for ping bypass?

**Comment by 3arthqu4ke** [comment]
Ok, after looking at the code for Openauth I found the following:
`"User has enabled double-authentication or must allow sign-in on https://account.live.com/activity"`
So check that for your account please.

 I will open an issue at OpenAuth so they can make it display this much more helpful message.

> Also, can someone let me know how to use mods if minecraft does launch for ping bypass?

You put them in your mods folder?

**Comment by hub50** [comment]
For the mods, I meant using headless console commands but I'll look more into that if it works. I don't have two-step verification enabled in Microsoft and I confirmed that the log-in from where my VPS is set is not malicious activity in https://account.live.com/activity. Beyond that, I am not sure how else to solve this error.

**Comment by 3arthqu4ke** [comment]
1. Hmm, what happens if you run HeadlessMc on your own machine instead of your VPS and log in?
2. Have you checked your E-Mail, Microsoft might have send you one.
3. Any chance you know how to use an IDE and a debugger?

**Comment by hub50** [comment]
1. Same error from my own machine.
2. I previously got an email for unusual sign-in activity which is expected but I confirmed it was me.
3. Yes, but I'm rusty.
Talking to other people who are familiar with ping bypass and Headlessmc, they said to use this In-Game Account Switcher mod https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher. This might be a solution but I am not sure how to run a mod such as this through the console so please advise if you think this is possible as it has been done before.

**Comment by 3arthqu4ke** [comment]
Can you try the zip you get from here: https://github.com/3arthqu4ke/HeadlessMc/actions/runs/2744995669
Please run it on your own machine first using the command `login -webview` which should open another window. If you want to do that on your VPS you would probably need a remote desktop. If you succeed to login you could copy the .json file from the HeadlessMc/auth directory over to the HeadlessMc/auth directory on your VPS. It contains an access and a refresh token.

> they said to use this In-Game Account Switcher mod

I can not allow HeadlessMc to launch the game without a valid Microsoft account, since that would make it a cracked Launcher, sorry.

**Comment by hub50** [comment]
Yes, this worked in getting me logged on however minecraft still launches and causes an error as most free trial VPSs don't support GPUs/OpenGL. Is there any way I can make it so the game does not render?

**Comment by 3arthqu4ke** [comment]
Yeah, that is the idea of headlessmc. You launch the game with the `-lwjgl` flag like this: `launch 1.12.2 -lwjgl`.

**Comment by hub50** [comment]
Yes, this works, but it results in this error at some point in the launch.
```
[04:29:38] [Thread-3/ERROR] [minecraft/SoundManager]: Error in class ''
[04:29:38] [Thread-3/ERROR] [minecraft/SoundManager]: Source 'c5fb0d58-3638-4284-be0a-b53e6fc890d0' not found in method 'play'
```

**Comment by 3arthqu4ke** [comment]
Oh this is just inconvenient spamming that you can remove using the -paulscode flag. So `launch 1.12.2 -lwjgl -paulscode`. For an overview you can type `help launch`. E.g. you can also patch the Log4j vulnerability.

**Comment by hub50** [comment]
One more error I'm getting, using paulscode and lwjgl flags, and the ping bypass jar in mods in .minecraft is this
`A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows Server 2016 (amd64) version 10.0
        Java Version: 1.8.0_202, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 120108640 bytes (114 MB) / 501743616 bytes (478 MB) up to 954728448 bytes (910 MB)
        JVM Flags: 0 total;
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State | ID         | Version      | Source                        | Signature                                |
        |:----- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
        | LCHI  | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
        | LCHI  | mcp        | 9.42         | minecraft.jar                 | None                                     |
        | LCHI  | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHI  | forge      | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHE  | pingbypass | 1.0.0        | pingbypass-1.0.0-release.jar  | None                                     |

        Loaded coremods (and transformers):
Core (pingbypass-1.0.0-release.jar)

        GL info: ' Vendor: '' Version: '' Renderer: ''
[05:10:57] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\myadmin04\AppData\Roaming\.minecraft\crash-reports\crash-2022-07-29_05.10.57-client.txt
[05:10:57] [Thread-5/INFO] [pingbypass]: Server closing...
Minecraft exited with code: -1`
Is it possible that the jar needs to be named PingBypass.jar and not pingbypass-1.0.0-release.jar?

**Comment by 3arthqu4ke** [comment]
You only sent the System info from the log, there has to be an Exception messag and Stacktrace somewhere.

**Comment by hub50** [comment]
Yes, followed the instructions there and this isn't first time getting this error.
```
[05:10:57] [Client thread/INFO] [pingbypass]: Binding to other empty to port: 127.0.0.0 : 51143.
[05:10:57] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Core (pingbypass-1.0.0-release.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 7/29/22 5:10 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PingBypass (pingbypass)
Caused by: java.net.BindException: Cannot assign requested address: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows Server 2016 (amd64) version 10.0
        Java Version: 1.8.0_202, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 120108640 bytes (114 MB) / 501743616 bytes (478 MB) up to 954728448 bytes (910 MB)
        JVM Flags: 0 total;
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State | ID         | Version      | Source                        | Signature                                |
        |:----- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
        | LCHI  | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
        | LCHI  | mcp        | 9.42         | minecraft.jar                 | None                                     |
        | LCHI  | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHI  | forge      | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHE  | pingbypass | 1.0.0        | pingbypass-1.0.0-release.jar  | None                                     |

        Loaded coremods (and transformers):
Core (pingbypass-1.0.0-release.jar)

        GL info: ' Vendor: '' Version: '' Renderer: ''
[05:10:57] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\myadmin04\AppData\Roaming\.minecraft\crash-reports\crash-2022-07-29_05.10.57-client.txt
[05:10:57] [Thread-5/INFO] [pingbypass]: Server closing...
Minecraft exited with code: -1
[05:11:00] [main/INFO] [LaunchCommand]: Deleting 26d4da32-3c3e-4228-b1ea-722c53c784a9
```

**Comment by 3arthqu4ke** [comment]
That port (51143) might be in use. Check that, also it needs to get forwarded. Also if you want to reach PingBypass from the outside it needs to be an external ip address not localhost.

**Comment by hub50** [comment]
Now I'm just trying to launch Minecraft with PingBypass in the vps. I will use a forwarded port in the Server.json once Minecraft runs. How would I change the port from 51143?

**Comment by 3arthqu4ke** [comment]
nvm its not the port try out 127.0.0.1?

**Comment by hub50** [comment]
Where would I change the IP address?

**Comment by 3arthqu4ke** [comment]
I think in the module config. Have not used PingBypass in a while and it is archived.

**Comment by hub50** [comment]
There is no module config. I see a config but no place for IP.

**Comment by 3arthqu4ke** [comment]
Screenshot?

**Comment by hub50** [comment]
![image](https://user-images.githubusercontent.com/88406665/181832460-95d5e860-989b-4d54-bc0f-fde774dce891.png)
![image](https://user-images.githubusercontent.com/88406665/181832521-97d258ac-a456-4f20-9b99-25068c38ba70.png)
Auth has .account json and nothing in the configs folder.

**Comment by 3arthqu4ke** [comment]
No not the HeadlessMc folder. I mean the one for the PingBypass. PingBypass and HeadlessMc are two very different projects.

**Comment by hub50** [comment]
![image](https://user-images.githubusercontent.com/88406665/181833434-cfbb6938-8408-46d2-9895-8347bc3e5cd5.png)

**Comment by 3arthqu4ke** [comment]
No I mean the folder where the game is running. Maybe inside .minecraft if u havent configured HeadlessMc differently.

**Comment by 3arthqu4ke** [comment]
## Installation
- Get a server, preferably hosted as close to the server you want to play on as possible.
- Install Java-8, the Minecraft 1.12.2 client and forge for that version on the server.
- Drag the PingBypass.jar into the mods folder on the server.
- Run the game once then close it, this should create the Server.json file in your servers minecraft folder which is used to configure the proxy.
- Open the file, type in IP and port.
- The IP should be the internal IP of your server (not 127.0.0.0), the port should be a forwarded port (not 25565 (minecraft) or other important ports).
- Now run the game, everything else is done from your pc.

**Comment by hub50** [comment]
![image](https://user-images.githubusercontent.com/88406665/181835688-bba4fb52-f3bb-4ff0-b499-ef8c49221e54.png)
Not sure exactly what you mean since there is nothing specifically called modules but I see the Server.json has been generated which is interesting because so far my minecraft has only crashed.
I decided to try it and with the ping bypass enabled I just get kicked everytime I join a server.

**Comment by 3arthqu4ke** [comment]
I cant say anything without logs/screenshots etc.
