### ISSUE TITLE
Issue when launching

### ISSUE THREAD

**Issue by Edouard127** [3arthqu4ke/HeadlessMc#25]
I'm running Windows 10, I used the bat provided in the latest release

`[13:31:18] [main/WARNING] [VersionService]: 1.16.5-forge-36.2.8.json: null
[13:31:18] [main/WARNING] [VersionService]: 1.17.1-forge-37.0.103.json: null
[13:31:18] [main/WARNING] [VersionService]: 1.17.1-forge-37.0.126.json: null
[13:31:19] [main/WARNING] [VersionService]: fabric-loader-0.11.7-1.16.5.json: null
[13:31:19] [main/WARNING] [VersionService]: fabric-loader-0.11.7-1.17.1.json: null
[13:31:19] [main/WARNING] [VersionService]: fabric-loader-0.12.5-1.17.1.json: null
[13:31:19] [main/WARNING] [VersionService]: fabric-loader-0.12.8-1.17.json: null
[13:31:19] [main/WARNING] [VersionService]: fabric-loader-0.12.8-1.18.json: null
Exception in thread "main" java.lang.NumberFormatException: For input string: "8.0"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at me.earth.headlessmc.launcher.version.JavaMajorVersionParser.parse(JavaMajorVersionParser.java:14)
        at me.earth.headlessmc.launcher.version.VersionFactory.parse(VersionFactory.java:27)
        at me.earth.headlessmc.launcher.version.DefaultVersionFactory.parse(DefaultVersionFactory.java:3)
        at me.earth.headlessmc.launcher.version.VersionService.read(VersionService.java:63)
        at me.earth.headlessmc.launcher.version.VersionService.update(VersionService.java:46)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:21)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:13)
        at me.earth.headlessmc.launcher.Main.main(Main.java:44)`
        
I have my jre/jdk path in the config file

**Comment by Edouard127** [comment]
Low priority, I can use it via docker :+1:

**Comment by 3arthqu4ke** [comment]
1. Could you send the output when you do `java -version` for the java versions you use?

2. I also see all these warnings: `[main/WARNING] [VersionService]: 1.16.5-forge-36.2.8.json: null`, does HeadlessMc find all Minecraft versions in your .minecraft/versions folder or does it not find some? You can check through `hmc versions`.

**Comment by 3arthqu4ke** [comment]
Also which version of HeadlessMc are you using that produces the NumberFormatException? I double checked and I do not see a way besides a) you are using an outdated version b) the dot in "8.0" is not a real dot????

**Comment by 3arthqu4ke** [comment]
OKOK, ignore what I said I am fixing this!

**Comment by 3arthqu4ke** [comment]
Can you please check out this version once it builds: https://github.com/3arthqu4ke/HeadlessMc/actions/runs/2793033621

**Comment by Edouard127** [comment]
Yes, sorry for the wait time

**Comment by Edouard127** [comment]
I no longer have the error @3arthqu4ke

**Comment by Edouard127** [comment]
However, I can't login using the args `--command login email <my email>` since it does not give me the context to enter the password

**Comment by 3arthqu4ke** [comment]
Are you really typing in `login email <my email>`? It is `login <email>`. Could not recreate yet.

**Comment by Edouard127** [comment]
Fixed
