### ISSUE TITLE
Error when joining a server on forge 1.12.2

### ISSUE THREAD

**Issue by Edouard127** [3arthqu4ke/HeadlessMc#28]
```
[02:55:34] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_332]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_332]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298) ~[brz.class:?]
        at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) ~[jh.class:?]
        at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) ~[jh.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 9 more
[02:55:34] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_332]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_332]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1876) ~[brz.class:?]
        at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:58) ~[iw.class:?]
        at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:11) ~[iw.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 9 more
```

The config

```
# suppress inspection "UnusedProperty" for whole file
# This config is for the docker container.
hmc.gamedir=/headlessmc/headlessmc-scripts/HeadlessMC/run
hmc.java.versions=/usr/local/openjdk-8/bin/java;/usr/java/openjdk-17/bin/java
hmc.invert.lwjgl.flag=true
hmc.invert.pauls.flag=true
hmc.store.accounts=true
!hmc.loglevel=DEBUG
hmc.gameargs=--server server ip --port 25565
```

**Comment by Edouard127** [comment]
I re-tested it, and it logged it

It's weird

**Comment by 3arthqu4ke** [comment]
Hmm, I do not really see how HeadlessMc could cause this. This looks more like an issue in Vanilla/Forge Minecraft to me. 

I am not sure if it is the same Exception but I vaguely remember getting so annoyed at something like this that I wrote something in 3arthh4ck (I am not sure if that really fixed the issue tho): https://github.com/3arthqu4ke/3arthh4ck/blob/main/src/main/java/me/earth/earthhack/forge/mixins/network/MixinNethandlerPlayClient.java and during that time HeadlessMc did not even exist, so I think this is not related to it. This should not occur too much, I hope.
