### ISSUE TITLE
Crashing on an headless linux vps with lwjgl option

### ISSUE THREAD

**Issue by CrazyDev-22** [3arthqu4ke/HeadlessMc#3]
launch 1.16.5-forge-36.2.22 -lwjgl
Launching version forge, 52ab7c90-bd90-4691-bcee-f6d000da4d4e
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-3.2.2.jar already exists!
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-jemalloc-3.2.2.jar already exists!
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-openal-3.2.2.jar already exists!
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-opengl-3.2.2.jar already exists!
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-glfw-3.2.2.jar already exists!
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-tinyfd-3.2.2.jar already exists!
[17:32:42] [main/WARNING] [Instrumentation]: /root/HeadlessMC/52ab7c90-bd90-4691-bcee-f6d000da4d4e/lwjgl-stb-3.2.2.jar already exists!
[17:32:46] [main/INFO] [ProcessFactory]: Game will run in /root/.minecraft
[17:32:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, fmlclient, --fml.forgeVersion, 36.2.22, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --username, CrazyDev22, --version, forge, --gameDir, /root/.minecraft, --assetsDir, /root/.minecraft/assets, --assetIndex, 1.16, --uuid, 65cefff027c74414a92a4ed1a709f609, --accessToken, ????????, --userType, msa, --versionType, release]
[17:32:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_312 by Private Build
[17:32:48] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17:32:48] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/root/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
Exception in thread "main" [17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Failed to create the GLFW window
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.fml.loading.progress.ClientVisualization.initWindow(ClientVisualization.java:104)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.fml.loading.progress.ClientVisualization.start(ClientVisualization.java:341)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.accept(EarlyProgressVisualization.java:43)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:190)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.util.HashMap$Values.forEach(HashMap.java:982)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[17:32:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Minecraft exited with code: 1

**Comment by 3arthqu4ke** [comment]
Will look into it as soon as possible!

**Comment by 3arthqu4ke** [comment]
In the meantime could you tell me what happens if you start the game without the `-lwjgl` option?

**Comment by 3arthqu4ke** [comment]
Please try the relase here: https://github.com/3arthqu4ke/HeadlessMc/releases/tag/1.0.4.a)

**Comment by CrazyDev-22** [comment]
works now. Thank you
