### ISSUE TITLE
Crash with -lwjgl flag

### ISSUE THREAD

**Issue by Edouard127** [3arthqu4ke/HeadlessMc#33]
Docker Info:
`Cloud integration: v1.0.23
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:53:11 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true`

Logs:
```
OpenJDK 64-Bit Server VM warning: You have loaded library /headlessmc/headlessmc-scripts/HeadlessMC/dfade622-7864-4b57-a4e7-4150f1000cc2/extracted/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[00:11:04] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: /headlessmc/headlessmc-scripts/HeadlessMC/dfade622-7864-4b57-a4e7-4150f1000cc2/extracted/liblwjgl64.so: libX11.so.6: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_332]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[?:1.8.0_332]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850) ~[?:1.8.0_332]
        at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[?:1.8.0_332]
        at java.lang.System.loadLibrary(System.java:1124) ~[?:1.8.0_332]
        at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_332]
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2984) ~[bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
        ... 6 more
Exception in thread "main" [00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.Runtime.exit(Runtime.java:107)
[00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.System.exit(System.java:973)
[00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[00:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Minecraft exited with code: 1
```

**Comment by Edouard127** [comment]
Doing the following command
`apt install openjdk-17-jdk`
Fixed the issue
But now here's the other error
```// Hey, that tickles! Hehehe!

Time: 9/1/22 12:19 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
        at net.minecraft.client.Minecraft.func_175594_ao(Minecraft.java:680)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:456)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.Display.<clinit>(Display.java:141)
        ... 10 more
Caused by: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.LinuxDisplay.openDisplay(Native Method)
        at org.lwjgl.opengl.LinuxDisplay.incDisplay(LinuxDisplay.java:305)
        at org.lwjgl.opengl.LinuxDisplay.internAtom(LinuxDisplay.java:629)
        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:734)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
        ... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at net.minecraft.client.Minecraft.func_175594_ao(Minecraft.java:680)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:456)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 5.10.102.1-microsoft-standard-WSL2
        Java Version: 1.8.0_332, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 194015392 bytes (185 MB) / 850919424 bytes (811 MB) up to 2213019648 bytes (2110 MB)
        JVM Flags: 0 total;
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML:
        Loaded coremods (and transformers):
LambdaCoreMod (lambda-3.2.1.jar)

        Launched Version: 1.12.2-forge-14.23.5.2860
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps:
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>```

**Comment by 3arthqu4ke** [comment]
On the docker image the lwjgl flag is added by default. Any chance you started the game with the -lwjgl flag? That might have caused it because it does the opposite on the docker image.

**Comment by 3arthqu4ke** [comment]
> Doing the following command
> `apt install openjdk-17-jdk`

That probably makes things worse? Java 17 is not needed for `1.12.2-forge-14.23.5.2860`.

I was able to use my docker container at 3arthqu4ke/headlessmc fine. All I did was login, download 1.12.2 and your forge version, download hmc-specifics, then `launch 0 -id`.

**Comment by 3arthqu4ke** [comment]
Yeah to sum up, the HeadlessMc config has `hmc.invert.lwjgl.flag=true`, that means you do not need to add the lwjgl flag.
