### ISSUE TITLE
Cant login with microsoft?

### ISSUE THREAD

**Issue by Tripp1e** [3arthqu4ke/HeadlessMc#38]
me.earth.headlessmc.launcher.auth.AuthException: Invalid credentials or tokens
        at me.earth.headlessmc.launcher.auth.AccountManager.login(AccountManager.java:62)
        at me.earth.headlessmc.launcher.command.login.LoginCommand.lambda$login$0(LoginCommand.java:56)
        at me.earth.headlessmc.launcher.command.login.PasswordCommand.execute(PasswordCommand.java:35)
        at me.earth.headlessmc.launcher.command.login.PasswordContext.fail(PasswordContext.java:37)
        at me.earth.headlessmc.command.CommandContextImpl.execute(CommandContextImpl.java:37)
        at me.earth.headlessmc.command.line.ConsoleListener.listen(ConsoleListener.java:22)
        at me.earth.headlessmc.command.line.CommandLineImpl.listen(CommandLineImpl.java:26)
        at me.earth.headlessmc.launcher.Main.runHeadlessMc(Main.java:90)
        at me.earth.headlessmc.launcher.Main.main(Main.java:35)
        
This is what I get

**Comment by Tripp1e** [comment]
please help, I still cant find the error

**Comment by 3arthqu4ke** [comment]
have you tried the command like this: `login yourEmail yourPassword`. Did you double check that your credentials are correct? Can you login via your browser and have you checked the credentials there?

**Comment by Tripp1e** [comment]
Yes I have. My credentials are correct. Is there maybe a problem with 2FA?

**Comment by 3arthqu4ke** [comment]
* You can check microsofts https://account.live.com/activity 
* Also you can try loging in with `login -webview`.

That is all I can do, works for me.

**Comment by Tripp1e** [comment]
On the website, it says successful login, but when you look at session activity it says additional review requested (may not be exactly that I just translated it) and when i try login -webview it just crashes the entire thing

**Comment by Tripp1e** [comment]
login -webview
Starting web view...
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at fr.litarvan.openauth.microsoft.MicrosoftAuthenticator.loginWithAsyncWebview(MicrosoftAuthenticator.java:159)
        at fr.litarvan.openauth.microsoft.MicrosoftAuthenticator.loginWithWebview(MicrosoftAuthenticator.java:145)
        at me.earth.headlessmc.launcher.auth.AccountManager.loginWithWebView(AccountManager.java:69)
        at me.earth.headlessmc.launcher.command.login.LoginCommand.loginWithWebView(LoginCommand.java:75)
        at me.earth.headlessmc.launcher.command.login.LoginCommand.execute(LoginCommand.java:25)
        at me.earth.headlessmc.command.CommandContextImpl.executeCommand(CommandContextImpl.java:43)
        at me.earth.headlessmc.command.CommandContextImpl.execute(CommandContextImpl.java:30)
        at me.earth.headlessmc.command.line.ConsoleListener.listen(ConsoleListener.java:22)
        at me.earth.headlessmc.command.line.CommandLineImpl.listen(CommandLineImpl.java:26)
        at me.earth.headlessmc.launcher.Main.runHeadlessMc(Main.java:90)
        at me.earth.headlessmc.launcher.Main.main(Main.java:35)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 more
        
        

This is the crashlog

**Comment by 3arthqu4ke** [comment]
-webview needs a jdk like jdk 8.

**Comment by Tripp1e** [comment]
I had jdk 17 set as JAVA_HOME and JAVA_PATH, so after I set it to 1.8, It wouldnt crash anymore, but now it opens a blank window titled Microsoft Authentication

**Comment by 3arthqu4ke** [comment]
It should only be blank for a second or so?

**Comment by Tripp1e** [comment]
I left it open for like 5 minutes and nothing happened
