### ISSUE TITLE
some dumb error that i dont get

### ISSUE THREAD

**Issue by Ceozz** [3arthqu4ke/HeadlessMc#39]
[11:08:13] [main/INFO] [ProcessFactory]: Downloading 1.8.9-forge1.8.9-11.15.1.2318-1.8.9 from https://launcher.mojang.com/v1/objects/3870888a6c3d349d3771a3e9d16c9bf5e076b908/client.jar
[11:08:14] [main/INFO] [Log4jPatcher]: Patching lookup in org/apache/logging/log4j/core/lookup/Interpolator
[11:08:14] [main/INFO] [Log4jPatcher]: Patching lookup in org/apache/logging/log4j/core/lookup/Interpolator
[11:08:14] [main/INFO] [Log4jPatcher]: Patching lookup in org/apache/logging/log4j/core/lookup/JndiLookup
[11:08:14] [main/INFO] [Log4jPatcher]: Patching lookup in org/apache/logging/log4j/core/lookup/JndiLookup
[11:08:16] [main/WARNING] [JavaService]: Couldn't find Java Version 8 falling back to 11
[11:08:16] [main/INFO] [Command]: Java version > 8 detected, deencapsulating!
[11:08:16] [main/INFO] [ProcessFactory]: Game will run in C:\Users\home\AppData\Roaming\.minecraft
[11:08:16] [main/INFO] [Main]: Initializing Runtime...
[11:08:16] [main/INFO] [Main]: Getting MainClass: net.minecraft.launchwrapper.Launch
[11:08:16] [main/INFO] [Main]: Calling main method: net.minecraft.launchwrapper.Launch
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at me.earth.headlessmc.runtime.Main.main(Main.java:38)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 5 more
Minecraft exited with code: 1

**Comment by 3arthqu4ke** [comment]
You need to install Java 8 and add it to the java versions in your config under hmc.java.versions.

**Comment by Ceozz** [comment]
oh i put the / wrong
