### ISSUE TITLE
 Invalid credentials or tokens and straight crash

### ISSUE THREAD

**Issue by kristupas098** [3arthqu4ke/HeadlessMc#44]
When i try to login i get this error message
Please use 'password <password>' to login. Use 'abort' to cancel the login process.

Logging in...
Failed to log you in: Invalid credentials or tokens
me.earth.headlessmc.launcher.auth.AuthException: Invalid credentials or tokens
        at me.earth.headlessmc.launcher.auth.AccountManager.login(AccountManager.java:62)
        at me.earth.headlessmc.launcher.command.login.LoginCommand.lambda$login$0(LoginCommand.java:56)
        at me.earth.headlessmc.launcher.command.login.PasswordCommand.execute(PasswordCommand.java:35)
        at me.earth.headlessmc.launcher.command.login.PasswordContext.fail(PasswordContext.java:37)
        at me.earth.headlessmc.command.CommandContextImpl.execute(CommandContextImpl.java:37)
        at me.earth.headlessmc.command.line.ConsoleListener.listen(ConsoleListener.java:22)
        at me.earth.headlessmc.command.line.CommandLineImpl.listen(CommandLineImpl.java:26)
        at me.earth.headlessmc.launcher.Main.runHeadlessMc(Main.java:90)
        at me.earth.headlessmc.launcher.Main.main(Main.java:35)
        
latest version

**Comment by 3arthqu4ke** [comment]
What did you enter after the "Please use 'password ' to login. Use 'abort' to cancel the login process."?
