### ISSUE TITLE
Not a JSON Object

### ISSUE THREAD

**Issue by Meowlan** [3arthqu4ke/HeadlessMc#63]
I am having trouble starting the launcher. When I try to launch it, I receive the following error message:

java.lang.IllegalStateException: Not a JSON Object: [{"name":"Meowlen","uuid":"8c382fa1-bef3-44f2-aeec-c0cd664eb1ba","expiresOn":"2021-02-21 11:02:04 +0100"}]
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at me.earth.headlessmc.launcher.version.VersionService.read(VersionService.java:63)
        at me.earth.headlessmc.launcher.version.VersionService.update(VersionService.java:46)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:21)
        at me.earth.headlessmc.launcher.Service.refresh(Service.java:13)
        at me.earth.headlessmc.launcher.Main.runHeadlessMc(Main.java:71)
        at me.earth.headlessmc.launcher.Main.main(Main.java:35)

**Comment by 3arthqu4ke** [comment]
I will see if I can make this more resilient, but I do not have much time right now.

For now, there seems to be a .json file inside your .minecraft/versions folder that does not belong there? With those contents: [{"name":"Meowlen","uuid":"8c382fa1-bef3-44f2-aeec-c0cd664eb1ba","expiresOn":"2021-02-21 11:02:04 +0100"}].

**Comment by Meowlan** [comment]
thank you so much, for what ever reason there was a usercache.json file inside one of my versions
