### ISSUE TITLE
Cannot login to microsoft account

### ISSUE THREAD

**Issue by 0xe0b69e** [3arthqu4ke/headlessmc#91]
```
Launching version 1.12.2, 21a8126f-3e16-433f-90b8-ff7da87d2730
me.earth.headlessmc.launcher.auth.AuthException: Invalid credentials or tokens
        at me.earth.headlessmc.launcher.auth.AccountManager.login(AccountManager.java:62)
        at me.earth.headlessmc.launcher.auth.AccountManager.login(AccountManager.java:40)
        at me.earth.headlessmc.launcher.launch.ProcessFactory.run(ProcessFactory.java:41)
        at me.earth.headlessmc.launcher.launch.ProcessFactory.run(ProcessFactory.java:34)
        at me.earth.headlessmc.launcher.command.LaunchCommand.execute(LaunchCommand.java:51)
        at me.earth.headlessmc.launcher.command.LaunchCommand.execute(LaunchCommand.java:19)
        at me.earth.headlessmc.launcher.command.FindByCommand.execute(FindByCommand.java:31)
        at me.earth.headlessmc.command.CommandContextImpl.executeCommand(CommandContextImpl.java:44)
        at me.earth.headlessmc.command.CommandContextImpl.execute(CommandContextImpl.java:31)
        at me.earth.headlessmc.command.line.ConsoleListener.listen(ConsoleListener.java:22)
        at me.earth.headlessmc.command.line.CommandLineImpl.listen(CommandLineImpl.java:26)
        at me.earth.headlessmc.launcher.Main.runHeadlessMc(Main.java:90)
        at me.earth.headlessmc.launcher.Main.main(Main.java:35)
Couldn't launch 1.12.2: Invalid credentials or tokens
[10:20:49] [main/INFO] [LaunchCommand]: Deleting 21a8126f-3e16-433f-90b8-ff7da87d2730
```

**Comment by alexking** [comment]
Ran into an issue like this, turned out I needed to login to my Microsoft account on my web browser to add a secondary email address

**Comment by JamJestJerzy** [comment]
> Ran into an issue like this, turned out I needed to login to my Microsoft account on my web browser to add a secondary email address

So adding secondary email and using it to login fixes the issue?

**Comment by 3arthqu4ke** [comment]
Have you also checked whats going on at https://account.live.com/activity?

**Comment by JamJestJerzy** [comment]
> Have you also checked whats going on at https://account.live.com/activity?

`Incorrect password entered`. My paassword is random sequence of characters, including for example `\` this may couse errors?

**Comment by 3arthqu4ke** [comment]
Oh I think so, will have to fix that. For now you have to escape every `\` with another `\`, so `\\`. You also need to escape `"` with `\`.

**Comment by 3arthqu4ke** [comment]
> Oh I think so, will have to fix that. For now you have to escape every `\` with another `\`, so `\\`. You also need to escape `"` with `\`.

Have you also tried this out?

**Comment by JamJestJerzy** [comment]
> > Oh I think so, will have to fix that. For now you have to escape every `\` with another `\`, so `\\`. You also need to escape `"` with `\`.
> 
> Have you also tried this out?

Yea, I tried
